hf: khalidalt/tydiqa-goldp
input_columns:
  - passage_text
  - question_text
output_column: answers
languages:
  - english
  - russian
  - indonesian
  - korean
  - arabic
  - finnish
  - bengali
  - telugu
  - swahili
language_names:
  - English
  - Russian
  - Indonesian
  - Korean
  - Arabic
  - Finnish
  - Bengali
  - Telugu
  - Swahili
index_split: train
test_split: validation

column_token_map:
  passage_text: </X1>
  question_text: </X2>
  answers: </A>
ice_token: </E>

completion_template:
  preprocess_func: process_qa
  ice_template: "</E></X1>\nQ:</X2>\nA:</A>"
  prompt_template: "</E></X1>\nQ:</X2>\nA:"

instruction_template:
  preprocess_func: process_qa
  ice_template: "</E></X1>\nQ: </X2>\nReferring to the passage above, the correct answer to the given question is:</A>"
  prompt_template: "</E></X1>\nQ: </X2>\nReferring to the passage above, the correct answer to the given question is:"

chat_template:
  preprocess_func: process_qa
  system: >
    You are an NLP assistant whose purpose is to solve reading comprehension problems in EVALUATION_LANGUAGE.
    You will be provided questions on a set of passages and you will need to provide the answer as it appears in the passage. 
    The answer should be in the same language as the question and the passage.
  input_template: "</X1>\nQ: </X2>\nReferring to the passage above, the correct answer to the given question is:"
  output_template: "</A>"

chat_template_star:
  preprocess_func: process_qa
  system: >
    You are an NLP assistant whose purpose is to solve extractive question answering problems in EVALUATION_LANGUAGE.
    Answer the question from the given passage.
    Your answer should be directly extracted from the passage and be a single entity, name, or number, not a sentence.
  input_template: "</X1>\nQ: </X2>\nThis is very important: Your answer should be directly extracted from the passage and be a single entity, 
    name, or number, not a sentence."
  output_template: "</A>"

